#!/bin/bash
#PBS -l nodes=4:ppn=16,walltime=00:1:54:00
#PBS -l gres=ccm
#PBS -r n
#PBS -o e.o/$PBS_JOBID.o
#PBS -e e.o/$PBS_JOBID.e
#PBS -q gpu
 
module load ccm
module load gcc
module swap PrgEnv-cray PrgEnv-gnu
module load namd/gnu/gpu/2.11
  
jobname=sim
logfile=${jobname}.log

cd $PBS_O_WORKDIR

# if [ -e $logfile ]; then
#    echo Log file already exists!
#    exit
# fi
let rep_num=$rep_num-1
mkdir -p output_000/{0..32}
mkdir output_000/dat

aprun -n 4 -N 1 -d 16 namd2 +idlepoll +ppn 8 +replicas 33 +CmiSpinOnIdle $jobname.conf +stdout output_000/%d/job0.%d.log >& $logfile
